//
// Generated by OFS script ofs_ip_cfg_db.tcl
//

// Include all generated configuration files
`include "ofs_ip_cfg_sys_clk.vh"
`include "ofs_ip_cfg_pcie_ss.vh"
`include "ofs_ip_cfg_soc_pcie_ss.vh"
`include "ofs_ip_cfg_hssi_ss.vh"
`include "ofs_ip_cfg_mem_ss.vh"
