//
// Generated by OFS script mem_ss_get_cfg.tcl using qsys-script
//

`ifndef __OFS_FIM_IP_CFG_MEM_SS__
`define __OFS_FIM_IP_CFG_MEM_SS__ 1


//
// Flags to enable memory channel instantiation/configuration
//
`define OFS_FIM_IP_CFG_MEM_SS_EN_MEM_3
`define OFS_FIM_IP_CFG_MEM_SS_EN_MEM_2
`define OFS_FIM_IP_CFG_MEM_SS_EN_MEM_1
`define OFS_FIM_IP_CFG_MEM_SS_EN_MEM_0
`define OFS_FIM_IP_CFG_MEM_SS_NUM_MEM_CHANNELS 4

//
// AXI-MM user interface configuration
//
`define OFS_FIM_IP_CFG_MEM_SS_DEFINES_USER_AXI 1
`define OFS_FIM_IP_CFG_MEM_SS_AXI_DATA_WIDTH 512
`define OFS_FIM_IP_CFG_MEM_SS_AXI_USER_WIDTH 1
`define OFS_FIM_IP_CFG_MEM_SS_AXI_LEN_WIDTH 8
`define OFS_FIM_IP_CFG_MEM_SS_AXI_ID_WIDTH 9
`define OFS_FIM_IP_CFG_MEM_SS_AXI_ADDR_WIDTH 32

//
// Fabric EMIF interface configuration
//
`define OFS_FIM_IP_CFG_MEM_SS_DEFINES_EMIF_DDR4 1
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_A_WIDTH 17
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_BA_WIDTH 2
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_BG_WIDTH 1
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_CK_WIDTH 1
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_CKE_WIDTH 1
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_CS_N_WIDTH 1
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_ODT_WIDTH 1
`define OFS_FIM_IP_CFG_MEM_SS_DDR4_DQ_WIDTH 32

`endif // `ifndef __OFS_FIM_IP_CFG_MEM_SS__
